spring:
  application:
    name: BackendBridge

  datasource:
    url: jdbc:mysql://localhost:3306/vigverse
    username: root
    password: ${DB_PASSWORD}  # Use an environment variable
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: "vigneshnalla888@gmail.com"
    password: ${MAIL_PASSWORD}  # Use an environment variable
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

project:
  poster: poster/

base:
  url: "http://localhost:8080"
